version: '2'
services:
    budenzauber-app:
        image: budenzauber
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://budenzauber-mariadb:3306/budenzauber
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 443:443
    budenzauber-mariadb:
        extends:
            file: mariadb.yml
            service: budenzauber-mariadb
